### ISSUE TITLE
CPAN Release?

### ISSUE THREAD

**Issue by matthewlenz** [vlyon/Plate#3]
You going to release this on CPAN at some point? :)

https://metacpan.org/release/Plate

**Comment by vlyon** [comment]
Hi Yes,

I've been trying to contact the PAUSE admins about a permissions issue, but I haven't received a response yet.
Once that's resolved I'll release it.

Vernon

**Comment by matthewlenz** [comment]
Looks like 0.4 is showing up now. :)

**Comment by matthewlenz** [comment]
Actually, this still isn't resolved.

**Comment by vlyon** [comment]
There was an issue with a previous (deleted) module named `plate` with a version number of `1.17`
Now resolved by bumping the version to `1.4`
